name: Deploy to AWS EC2

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/app
            # if git not setup then it clone it otherwise pull
            if [ ! -d ".git" ]; then
              git clone https://github.com/Rayhan108/el-afrik.git .
            else
              git pull origin main
            fi
            
            npm install
            npm run build
            # app restart using PM2 
            pm2 delete el-afrik || true
            pm2 start dist/server.js --name "el-afrik"
            pm2 save