name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # NVM এবং Node লোড করা (npm/pm2 পাওয়ার জন্য)
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            
            mkdir -p ~/app
            cd ~/app
            
            if [ ! -d ".git" ]; then
              git init
              git remote add origin https://github.com/sparktechagency/elafrik_backend.git
            fi
            
            git fetch --all

            git reset --hard origin/main
            
            npm install
            
            npm run build
            
            pm2 delete el-afrik || true
            pm2 start dist/server.js --name "el-afrik"
           
            pm2 save